[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino

; Kích hoạt chuẩn TinyUSB cho S2 (rất quan trọng)
; Không dùng ARDUINO_USB_MODE=1 ở đây vì lolin_s2_mini mặc định là 0 (Tức là dùng TinyUSB)
build_flags = 
    -D USE_TINYUSB